# A comprehensive list of introspective writing prompts
prompts = [
    "Describe a time when you had a sense of flow.",
    "What's one thing you could improve about your desk?",
    "What's one unnecessary step you could remove from your <some life thing> process?",
    "If money was no object, what would you do differently?",
    "What does success in <some project, or in love, or in a project> look like to you? How do you know when you have achieved this?",
    "Once AGI has been achieved and you have a personal assistant who can help you train and be mindful, how will you live?",
    "Reflect on a moment when you felt truly at peace. What were you doing?",
    "What is one habit you wish to cultivate, and why?",
    "Imagine your ideal day. What activities fill your time?",
    "If you could master any skill instantly, what would it be and why?",
    "Describe a place that makes you feel safe and why it has that effect on you.",
    "What is one thing you wish you could change about your daily routine?",
    "Think about a time when you felt proud of yourself. What happened?",
    "If you could have dinner with any historical figure, who would it be and why?",
    "What is one goal you have for the next year, and what steps will you take to achieve it?",
    "Describe a time when you helped someone. How did it make you feel?",
    "What is one thing you are grateful for today, and why?",
    "If you could live anywhere in the world, where would it be and why?",
    "What is one book or movie that has significantly impacted your life?",
    "Imagine you are writing a letter to your younger self. What advice would you give?",
    "What is one thing you wish people knew about you?",
    "Describe a time when you had to make a difficult decision. What was the outcome?",
    "If you could change one thing about the world, what would it be and why?",
    "What is one thing you would like to learn more about, and why?",
    "Reflect on a time when you felt inspired. What sparked that inspiration?",
    "What is one thing you would like to accomplish before the end of the year?",
    "Describe a person who has had a significant impact on your life. What did they teach you?",
    "What is one thing you would like to do more of in your free time?",
    "If you could relive any moment in your life, what would it be and why?",
    "What is one thing you would like to improve about your communication skills?",
    "Imagine you are writing a story about your life. What is the title and why?",
    "What is one thing you would like to change about your work environment?",
    "Describe a time when you felt truly connected to someone. What made that connection special?",
    "What is one thing you would like to do differently in your personal relationships?",
    "If you could have any superpower, what would it be and why?",
    "What is one thing you would like to achieve in your career, and how will you get there?",
    "Reflect on a time when you felt challenged. How did you overcome it?",
    "What is one thing you would like to do to improve your health and well-being?",
    "Imagine you are planning a perfect weekend. What activities would you include?",
    "What is one thing you would like to do to give back to your community?",
    "Describe a time when you felt truly happy. What contributed to that happiness?"
]