[mindfulness_reminders]
reminder_1 = "Remember to return to your breathing, continue coding but choose one muscle group, tighten it at a gradually increasing intensity from 1 to 5, then relax it gradually from 5 to negative two."
reminder_2 = "Take a second to adjust your distance from computer and keyboard. Check in with your posture."
reminder_3 = "Take a second to tune in to the things in your peripheral vision." 