name: "Structure"
description: "Mindful screentime and project management."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  provider: ^6.0.1
  build_runner: ^2.4.13
  drift: ^2.21.0
  drift_flutter: ^0.2.1
  sqlite3_flutter_libs: ^0.5.26
  path_provider: ^2.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  font_awesome_flutter: ^10.8.0
  icons_plus: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  rename: 3.0.2


flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
